### ISSUE TITLE
examples can't be tried because openindustrialdata.com is down

### ISSUE THREAD

**Issue by cwinkelmann** [cognitedata/ml-examples#2]
It is stated in https://github.com/cognitedata/ml-examples/blob/master/basics/Learn%20to%20use%20CDP.ipynb an API key is needed, but it seems http://openindustrialdata.com/ is down.

A ``` $ whois openindustrialdata.com ``` revealed the domain exists but it can't even be pinged.
Because of this, there is no way an API key can be generated.

Is there a workaround for this?

Regards
Christian Winkelmann

**Comment by matiashf-cognite** [comment]
Hi Christian! Thanks for letting us know. :+1: [openindustrialdata.com](https://openindustrialdata.com) is now up and running, and you should be able to get an API key there.

**Comment by cwinkelmann** [comment]
Thanks, I managed to get a working API key now.
